### PR TITLE
Raise supported php version to 8.1+ and symfony version to 6.x, drop …

### PR DESCRIPTION
**Pull request by temp**
…support for older versions

Sadly I wasn't able to create a version that supports symfony 5+6 and older php versions.
Maybe this could be released as a new major version 4.0, older php/symfony version could still use 3.x.

A lot of stuff has been updated:
- switch to friends-of-behat packages for the behat-extensions
- upgrade web-token/* to 3.x
- upgrade safe to 2.x
- upgrade phpstan to 1.x

Removed the travis-tests and moved to github actions.

Tested in our project that uses azure based authentication, works fine with symfony 6.

### CODE REVIEW

**Comment by lucasgranberg** [comment]
This looks really promising, any particular reason you removed thecodingmachine/safe for "safe" sprintf? Sprintf seems to be used only for Exception messages so maybe not that big of a deal?

**Comment by temp** [comment]
Since PHP 8.x sprintf itself is safe, so thecodingmachine/safe is not needed anymore.
And PHP 8.0 is required for symfony/*
See https://github.com/thecodingmachine/safe/blob/master/deprecated/strings.php#L299

**Comment by Spomky** [comment]
Excellent. Many thanks for this PR.
This is something I wanted to do but had no time to dig into it

**Comment by Spomky** [comment]
Would it be possible to:

* Drop FriendsOfPHP/PHP-CS-Fixer in favor of [symplify/easy-coding-standard](https://github.com/symplify/easy-coding-standard). You can  use [this config file](https://github.com/web-auth/webauthn-framework/blob/v4.0/ecs.php) as a start.
* I really like [Rector](https://github.com/rectorphp/rector) for code migration. See and https://github.com/web-auth/webauthn-framework/blob/v4.0/rector.php (to be changed if needed)

Do you think it is reasonable to require at least PHP8.1 for such bundle?

**Comment by temp** [comment]
Since I have neither excperience with php-cs-fixer nor easy-coding-standard (we are only using phpcs), I don't know if this should be part of this PR.
Also, rector is something that's not done quickly (in our experience), so again I'm against delaying this PR for rector.
All tests are green right now, this would only artificially expand this PR.

On the other hand it would of course be great to move to easy-coding-standard and rector in the long run. Maybe this could be developed in a seperate branch?

And for PHP 8.1 - I see no reason, Symfony has 8.0+, and like I said above, all tests are green for now. But it would of course be possible.

**Comment by Spomky** [comment]
Ok @temp. Thank you for your advices.

**Comment by Spomky** [comment]
I've just created a new branch v4.0 and merged another PR.
Let me just test it before and we are good to go.

**Comment by Spomky** [comment]
OK let's go with this new branch.
Many thanks!

**Comment by temp** [comment]
Awesome!

**Comment by temp** [comment]
@Spomky when will you create a release for 4.0, after your rector/ecs changes?

**Comment by Spomky** [comment]
It seems to be ready now. I don't see any other modification.
Also, I created a dedicated Flex Repository and it works fine (https://github.com/Spomky-Labs/lexik-jose-bridge#symfony-flex).

**Comment by temp** [comment]
Nice! Will try it out when a tagged release is available.

**Comment by Spomky** [comment]
Tagged!
Let me know if something is wrong

**Pull request merged**
